// Code generated by probing OpenSearch 3.8.0 (default distribution with
// bundled plugins); DO NOT EDIT. Columns: key, kind, flags, JSON default,
// min, max (see settings.go).

package engine

const indexSettingTable = `index.aggregation.streaming.min_segment_size	i	D	"1000"	1	
index.allocation.existing_shards_allocator	s	P	"gateway_allocator"		
index.allocation.max_retries	i	D	"5"	0	
index.analyze.max_token_count	i	D	"10000"	1	
index.append_only.enabled	b		"false"		
index.auto_expand_replicas	x	D	"false"		
index.auto_expand_search_replicas	x	D	"false"		
index.auto_force_merge.enabled	b	D	"true"		
index.blocks.metadata	b	D	"false"		
index.blocks.read	b	D	"false"		
index.blocks.read_only	b	D	"false"		
index.blocks.read_only_allow_delete	b	D	"false"		
index.blocks.search_only	b	D	"false"		
index.blocks.write	b	D	"false"		
index.bulk.adaptive_shard_selection.enabled	b	D	"false"		
index.check_pending_flush.enabled	b		"true"		
index.codec	x		"default"		
index.codec.compression_level	x		"3"		
index.codec.qatmode	x	D	"auto"		
index.composite_index	b		"false"		
index.composite_index.star_tree.default.max_leaf_docs	i		"10000"	1	
index.composite_index.star_tree.field.default.date_intervals	L		["minute", "half-hour"]		
index.composite_index.star_tree.field.default.metrics	L		["VALUE_COUNT", "SUM"]		
index.composite_index.star_tree.field.max_base_metrics	i		"100"	4	
index.composite_index.star_tree.field.max_date_intervals	i		"3"	1	
index.composite_index.star_tree.field.max_dimensions	i		"10"	2	
index.composite_index.star_tree.max_fields	i		"1"	1	
index.composite_store.type	x		"default"		
index.compound_format	x	D	"0.1"		
index.context.created_version	l	P	"0"	0	
index.context.current_version	l	P	"0"	0	
index.context_aware.enabled	b		"false"		
index.context_aware.max_retry_on_lookup_map_acquisition_exception	i	D	"15"	5	
index.correlation	b		"false"		
index.creation_date	l		"-1"	-1	
index.data_path	x		""		
index.default_pipeline	s	D	"_none"		
index.derived_source.enabled	b		"false"		
index.derived_source.translog.enabled	b	D	"false"		
index.fielddata.cache	x		"node"		
index.final_pipeline	s	D	"_none"		
index.flush_after_merge	z	D	"512mb"		
index.force_memory_term_dictionary	b		"false"		
index.format	i		"0"		
index.gc_deletes	t	D	"60s"		
index.hidden	b	D	"false"		
index.highlight.max_analyzed_offset	i	D	"1000000"	1	
index.history.uuid	s	P	"_na_"		
index.indexing.slowlog.level	x	D	"TRACE"		
index.indexing.slowlog.reformat	b	D	"true"		
index.indexing.slowlog.source	x	D	"1000"		
index.indexing.slowlog.threshold.index.debug	t	D	"-1"		
index.indexing.slowlog.threshold.index.info	t	D	"-1"		
index.indexing.slowlog.threshold.index.trace	t	D	"-1"		
index.indexing.slowlog.threshold.index.warn	t	D	"-1"		
index.ingestion_source.all_active	b		"false"		
index.ingestion_source.error_strategy	x	D	"DROP"		
index.ingestion_source.internal_queue_size	i		"100"	1	
index.ingestion_source.mapper_type	x		"default"		
index.ingestion_source.num_processor_threads	i		"1"	1	
index.ingestion_source.pointer.init.reset	x		"LATEST"		
index.ingestion_source.pointer.init.reset.value	s		""		
index.ingestion_source.pointer_based_lag_update_interval	t		"10s"	0ms	
index.ingestion_source.poll.max_batch_size	l	D	"1000"	0	
index.ingestion_source.poll.timeout	i	D	"1000"	0	
index.ingestion_source.type	s		"none"		
index.ingestion_source.warmup.lag_threshold	l	D	"100"	0	
index.ingestion_source.warmup.timeout	t	D	"-1"		
index.knn	b		"false"		
index.knn.advanced.approximate_threshold	i	D	"0"	-1	
index.knn.advanced.filtered_exact_search_threshold	i	D	"-1"		
index.knn.algo_param.ef_search	i	D	"100"	2	
index.knn.derived_source.enabled	x		"false"		
index.knn.disk.vector.shard_level_rescoring_disabled	b	D	"false"		
index.knn.faiss.efficient_filter.disable_exact_search	b	D	"false"		
index.knn.memory_optimized_search	b		"false"		
index.knn.remote_index_build.enabled	b	D	"true"		
index.knn.remote_index_build.size.min	z	D	"52428800b"		
index.load_fixed_bitset_filters_eagerly	b		"true"		
index.ltrstore_version	i		"2"	-1	
index.mapper.dynamic	b	D	"true"		
index.mapping.coerce	b		"false"		
index.mapping.depth.limit	x	D	"20"		
index.mapping.dynamic_properties.lucene_field.limit	l	D	"10000"	0	
index.mapping.field_name_length.limit	x	D	"50000"		
index.mapping.ignore_malformed	b		"false"		
index.mapping.nested_fields.limit	l	D	"50"	0	
index.mapping.nested_objects.limit	l	D	"10000"	0	
index.mapping.total_fields.limit	l	D	"1000"	0	
index.max_adjacency_matrix_filters	i	D	"100"	2	
index.max_docvalue_fields_search	i	D	"100"	0	
index.max_inner_result_window	i	D	"100"	1	
index.max_ngram_diff	i	D	"1"	0	
index.max_refresh_listeners	i	D	"1000"	0	
index.max_regex_length	i	D	"1000"	1	
index.max_rescore_window	i	D	"10000"	1	
index.max_result_window	i	D	"10000"	1	
index.max_script_fields	i	D	"32"	0	
index.max_shingle_diff	i	D	"3"	0	
index.max_slices_per_pit	i	D	"1024"	1	
index.max_slices_per_scroll	i	D	"1024"	1	
index.max_terms_count	i	D	"65536"	1	
index.merge.log_byte_size_policy.max_merge_segment	z	D	"5368709120b"		
index.merge.log_byte_size_policy.max_merge_segment_forced_merge	z	D	"9223372036854775807b"		
index.merge.log_byte_size_policy.max_merged_docs	i	D	"2147483647"		
index.merge.log_byte_size_policy.merge_factor	i	D	"10"	2	
index.merge.log_byte_size_policy.min_merge	z	D	"16777216b"		
index.merge.log_byte_size_policy.no_cfs_ratio	x	D	"0.1"		
index.merge.policy	x		"default"		
index.merge.policy.deletes_pct_allowed	d	D	"20.0"	5.0	50.0
index.merge.policy.expunge_deletes_allowed	d	D	"10.0"	0.0	
index.merge.policy.floor_segment	z	D	"16777216b"		
index.merge.policy.max_merge_at_once	i	D	"30"	2	
index.merge.policy.max_merged_segment	z	D	"5368709120b"		
index.merge.policy.reclaim_deletes_weight	d	D	"2.0"	0.0	
index.merge.policy.segments_per_tier	d	D	"10.0"	2.0	
index.merge.scheduler.auto_throttle	b	D	"true"		
index.merge.scheduler.max_force_merge_mb_per_sec	d	D	"Infinity"	0.0	
index.merge.scheduler.max_merge_count	i	D	"9"	1	
index.merge.scheduler.max_thread_count	i	D	"4"	1	
index.merge_on_flush.enabled	b	D	"true"		
index.merge_on_flush.max_full_flush_merge_wait_time	t	D	"10s"	1ms	
index.merge_on_flush.policy	x	D	"default"		
index.neural_search.hybrid_collapse_docs_per_group_per_subquery	i	D	"0"	0	
index.neural_search.semantic_ingest_batch_size	i	D	"10"	1	
index.number_of_replicas	i	D	"1"	0	
index.number_of_routing_shards	i	F	"1"	1	
index.number_of_search_replicas	i	D	"0"	0	
index.number_of_shards	i	F	"1"	1	1024
index.number_of_virtual_shards	i		"-1"	-1	
index.opendistro.index_state_management.auto_manage	b	D	"true"		
index.opendistro.index_state_management.policy_id	s	D	""		
index.opendistro.index_state_management.rollover_alias	s	D	""		
index.opendistro.index_state_management.rollover_skip	b	D	"false"		
index.opendistro.rollup_index	b	I	"false"		
index.optimize_auto_generated_id	b	D	"true"		
index.optimize_doc_id_lookup.fuzzy_set.enabled	b	D	"false"		
index.optimize_doc_id_lookup.fuzzy_set.false_positive_probability	d	D	"0.2047"	0.01	0.5
index.percolator.map_unmapped_fields_as_text	b		"false"		
index.periodic_flush_interval	t	D	"-1"		
index.pluggable.dataformat	s		""		
index.pluggable.dataformat.enabled	b		"false"		
index.plugins.index_state_management.auto_manage	b	D	"true"		
index.plugins.index_state_management.policy_id	s	D	""		
index.plugins.index_state_management.rollover_alias	s	D	""		
index.plugins.index_state_management.rollover_skip	b	D	"false"		
index.plugins.replication.follower.leader_index	s	I	""		
index.plugins.replication.follower.ops_batch_size	i	D	"50000"	16	
index.plugins.replication.translog.retention_lease.pruning.enabled	b	D	"false"		
index.plugins.replication.translog.retention_size	z	D	"536870912b"		
index.plugins.rollup_index	b	D	"false"		
index.priority	i	D	"1"	0	
index.queries.cache.enabled	b		"true"		
index.query.default_field	L	D	["*"]		
index.query.derived_field.enabled	b	D	"true"		
index.query.max_nested_depth	i	D	"20"	1	
index.query.parse.allow_unmapped_fields	b		"true"		
index.query_string.lenient	b		"false"		
index.recovery.type	x		""		
index.refresh_interval	t	D	"1s"		
index.remote_store.enabled	b	P	"false"		
index.remote_store.segment.repository	s	P	""		
index.remote_store.translog.buffer_interval	t	D	"650ms"	0ms	
index.remote_store.translog.keep_extra_gen	i	D	"100"	0	
index.remote_store.translog.repository	s	P	""		
index.replication.type	x	F	"DOCUMENT"		
index.requests.cache.enable	b	D	"true"		
index.routing.allocation.enable	x	D	"all"		
index.routing.allocation.total_primary_shards_per_node	i	D	"-1"	-1	
index.routing.allocation.total_remote_capable_primary_shards_per_node	i	D	"-1"	-1	
index.routing.allocation.total_remote_capable_shards_per_node	i	D	"-1"	-1	
index.routing.allocation.total_shards_per_node	i	D	"-1"	-1	
index.routing.rebalance.enable	x	D	"all"		
index.routing_partition_size	i	F	"1"	1	
index.search.concurrent.max_slice_count	i	D	"4"	0	
index.search.concurrent_segment_search.enabled	b	D	"false"		
index.search.concurrent_segment_search.mode	x	D	"none"		
index.search.default_pipeline	s	D	"_none"		
index.search.idle.after	t	D	"30s"	0m	
index.search.slowlog.level	x	D	"TRACE"		
index.search.slowlog.threshold.fetch.debug	t	D	"-1"		
index.search.slowlog.threshold.fetch.info	t	D	"-1"		
index.search.slowlog.threshold.fetch.trace	t	D	"-1"		
index.search.slowlog.threshold.fetch.warn	t	D	"-1"		
index.search.slowlog.threshold.query.debug	t	D	"-1"		
index.search.slowlog.threshold.query.info	t	D	"-1"		
index.search.slowlog.threshold.query.trace	t	D	"-1"		
index.search.slowlog.threshold.query.warn	t	D	"-1"		
index.search.star_tree_index.enabled	b	D	"true"		
index.search.throttled	b	P	"false"		
index.searchable_snapshot.index.id	s	I	""		
index.searchable_snapshot.repository	s	I	""		
index.searchable_snapshot.shard_path_type	x	I	"FIXED"		
index.searchable_snapshot.snapshot_id.name	s	I	""		
index.searchable_snapshot.snapshot_id.uuid	s	I	""		
index.segment_replication.publish_referenced_segments_interval	t	D	"10m"	1s	
index.shard.check_on_startup	x		"false"		
index.soft_deletes.enabled	b	F	"true"		
index.soft_deletes.retention.operations	l	D	"0"	0	
index.soft_deletes.retention_lease.period	t	D	"12h"	0ms	
index.sort.field	x	F	[]		
index.sort.missing	x	F	[]		
index.sort.mode	x	F	[]		
index.sort.order	x	F	[]		
index.sparse	b		"false"		
index.store.data_locality	x		"FULL"		
index.store.factory	x		""		
index.store.fs.fs_lock	x		"native"		
index.store.hybrid.nio.extensions	L		["segments_N", "write.lock", "si", "cfe", "fnm", "fdx", "fdt", "pos", "pay", "nvm", "dvm", "tvx", "tvd", "liv", "dii", "vem"]		
index.store.preload	L		[]		
index.store.stats_refresh_interval	t		"10s"		
index.store.type	x		""		
index.tiered.storage.slowlog.enabled	b	D	"false"		
index.tiered.storage.slowlog.level	x	D	"TRACE"		
index.tiered.storage.slowlog.threshold.fetch.debug	t	D	"2000ms"		
index.tiered.storage.slowlog.threshold.fetch.info	t	D	"5000ms"		
index.tiered.storage.slowlog.threshold.fetch.trace	t	D	"500ms"		
index.tiered.storage.slowlog.threshold.fetch.warn	t	D	"10000ms"		
index.tiered.storage.slowlog.threshold.query.debug	t	D	"2000ms"		
index.tiered.storage.slowlog.threshold.query.info	t	D	"5000ms"		
index.tiered.storage.slowlog.threshold.query.trace	t	D	"500ms"		
index.tiered.storage.slowlog.threshold.query.warn	t	D	"10000ms"		
index.tiering.state	s	P	"HOT"		
index.translog.durability	x	D	"REQUEST"		
index.translog.flush_threshold_size	z	D	"512mb"		
index.translog.generation_threshold_size	z	D	"64mb"		
index.translog.read_forward	b		"false"		
index.translog.retention.age	t	D	"-1"		
index.translog.retention.size	z	D	"-1"		
index.translog.sync_interval	t	D	"5s"	100ms	
index.unassigned.node_left.delayed_timeout	t	D	"1m"	0ms	
index.unreferenced_file_cleanup.enabled	b	D	"true"		
index.use_compound_file	b		"true"		
index.uuid	s	P	"_na_"		
index.verified_before_close	b	P	"false"		
index.version.created	i	P	""		
index.warm	b		"false"		
index.warmer.enabled	b	D	"true"		
index.write.wait_for_active_shards	x	D	"1"		
`

const clusterSettingTable = `action.auto_create_index	s	D	"true"		
action.destructive_requires_name	b	D	"false"		
action.search.shard_count.limit	l	D	"9223372036854775807"	1	
admission_control.cluster.admin.cpu_usage.limit	l	D	"95"		
admission_control.cluster_admin.native_memory_usage.limit	l	D	"95"		
admission_control.indexing.cpu_usage.limit	l	D	"95"		
admission_control.indexing.io_usage.limit	l	D	"95"		
admission_control.indexing.native_memory_pool_usage.limit	l	D	"90"	0	
admission_control.indexing.native_memory_usage.limit	l	D	"95"		
admission_control.search.cpu_usage.limit	l	D	"95"		
admission_control.search.io_usage.limit	l	D	"95"		
admission_control.search.native_memory_usage.limit	l	D	"95"		
admission_control.transport.cpu_usage.mode_override	s	D	"disabled"		
admission_control.transport.io_usage.mode_override	s	D	"disabled"		
admission_control.transport.mode	s	D	"disabled"		
admission_control.transport.native_memory_usage.mode_override	s	D	"disabled"		
cat.indices.response.limit.number_of_indices	i	D	"-1"		
cat.segments.response.limit.number_of_indices	i	D	"-1"		
cat.shards.response.limit.number_of_shards	i	D	"-1"		
cluster.allocator.gateway.batch_size	l	D	"2000"	1	10000
cluster.application_templates.enabled	b	D	"false"		
cluster.auto_force_merge.enabled	b	D	"false"		
cluster.auto_shrink_voting_configuration	b	D	"true"		
cluster.blocks.create_index	b	D	"false"		
cluster.blocks.create_index.auto_release	b	D	"true"		
cluster.blocks.read_only	b	D	"false"		
cluster.blocks.read_only_allow_delete	b	D	"false"		
cluster.default.index.max_merge_at_once	i	D	"30"	2	
cluster.default.index.refresh_interval	t	D	"1s"		
cluster.default_number_of_replicas	i	D	"1"		
cluster.fault_detection.follower_check.interval	t	D	"1000ms"	100ms	
cluster.fault_detection.follower_check.timeout	t	D	"10000ms"	1ms	150000ms
cluster.fault_detection.leader_check.timeout	t	D	"10000ms"	1ms	60000ms
cluster.filecache.activeusage.indexing.threshold	r	D	"90%"		
cluster.filecache.activeusage.search.threshold	r	D	"100%"		
cluster.filecache.activeusage.threshold.enabled	b	D	"true"		
cluster.filecache.remote_data_ratio	d	D	"5.0"	1.0	
cluster.follower_lag.timeout	t	D	"90000ms"	1ms	
cluster.ignore_dot_indexes	b	D	"false"		
cluster.index.merge.scheduler.auto_throttle	b	D	"true"		
cluster.index.merge.scheduler.max_merge_count	i	D	"9"		
cluster.index.merge.scheduler.max_thread_count	i	D	"4"		
cluster.index.refresh.fixed_interval_scheduling.enabled	b	D	"false"		
cluster.index.refresh.shard_level.enabled	b	D	"false"		
cluster.indices.close.enable	b	D	"true"		
cluster.info.update.interval	t	D	"30s"	10s	
cluster.info.update.timeout	t	D	"15s"	0ms	
cluster.ingest.max_number_processors	i	D	"2147483647"	1	
cluster.ingest.system_pipeline_enabled	b	D	"true"		
cluster.max_remote_capable_shards_per_node	i	D	"1000"	1	
cluster.max_shards_per_node	i	D	"1000"	1	
cluster.max_voting_config_exclusions	i	D	"10"	1	
cluster.merge.scheduler.max_force_merge_mb_per_sec	d	D	"Infinity"	0.0	
cluster.metadata.perf_analyzer.collectors.mode	i	D	"0"		
cluster.metadata.perf_analyzer.config.overrides	s	D	""		
cluster.metadata.perf_analyzer.pa_node_stats_setting	i	D	"1"		
cluster.metadata.perf_analyzer.state	i	D	"0"		
cluster.migration.direction	s	D	"NONE"		
cluster.minimum.index.refresh_interval	t	D	"0ms"	0ms	
cluster.no_cluster_manager_block	x	D	"metadata_write"		
cluster.no_master_block	x	D	"metadata_write"		
cluster.persistent_tasks.allocation.enable	s	D	"all"		
cluster.persistent_tasks.allocation.recheck_interval	t	D	"30s"	10s	
cluster.pluggable.dataformat	s	D	""		
cluster.pluggable.dataformat.enabled	b	D	"false"		
cluster.publish.timeout	t	D	"30000ms"	1ms	
cluster.remote_state.download.serve_read_api.enabled	b	D	"true"		
cluster.remote_store.compatibility_mode	s	D	"STRICT"		
cluster.remote_store.index.path.hash_algorithm	s	D	"FNV_1A_COMPOSITE_1"		
cluster.remote_store.index.path.type	s	D	"HASHED_PREFIX"		
cluster.remote_store.index.segment_metadata.retention.max_count	i	D	"10"	-1	
cluster.remote_store.index.translog.translog_metadata	b	D	"true"		
cluster.remote_store.index_metadata.path_hash_algo	s	D	"FNV_1A_BASE64"		
cluster.remote_store.index_metadata.path_type	s	D	"HASHED_PREFIX"		
cluster.remote_store.publication.enabled	b	D	"false"		
cluster.remote_store.routing_table.path_hash_algo	s	D	"FNV_1A_BASE64"		
cluster.remote_store.routing_table.path_type	s	D	"HASHED_PREFIX"		
cluster.remote_store.segment.transfer_timeout	t	D	"30m"	10m	
cluster.remote_store.server_side_encryption	b	D	"true"		
cluster.remote_store.state.checksum_validation.mode	s	D	"NONE"		
cluster.remote_store.state.cleanup.batch_size	i	D	"1000"	0	
cluster.remote_store.state.cleanup.max_batches	i	D	"3"	1	
cluster.remote_store.state.cleanup_interval	t	D	"5m"		
cluster.remote_store.state.global_metadata.upload_timeout	t	D	"20000ms"		
cluster.remote_store.state.index_metadata.upload_timeout	t	D	"20000ms"		
cluster.remote_store.state.metadata_manifest.upload_timeout	t	D	"20000ms"		
cluster.remote_store.state.read_timeout	t	D	"20000ms"		
cluster.remote_store.translog.buffer_interval	t	D	"650ms"	0ms	
cluster.remote_store.translog.max_readers	i	D	"1000"	-1	
cluster.remote_store.translog.transfer_timeout	t	D	"30s"	30s	
cluster.remote_store.uploaded_segments_cleanup_threshold	i	D	"1000"	-1	
cluster.restrict.pluggable.dataformat	b	D	"false"		
cluster.routing.allocation.allow_rebalance	x	D	"indices_all_active"		
cluster.routing.allocation.awareness.attributes	L	D	[]		
cluster.routing.allocation.awareness.balance	b	D	"false"		
cluster.routing.allocation.balance.index	d	D	"0.55"	0.0	
cluster.routing.allocation.balance.prefer_primary	b	D	"false"		
cluster.routing.allocation.balance.shard	d	D	"0.45"	0.0	
cluster.routing.allocation.balance.threshold	d	D	"1.0"	0.0	
cluster.routing.allocation.balanced_shards_allocator.allocator_timeout	t	D	"-1"		
cluster.routing.allocation.balanced_shards_allocator.schedule_reroute.priority	s	D	"NORMAL"		
cluster.routing.allocation.cluster_concurrent_rebalance	i	D	"2"	-1	
cluster.routing.allocation.cluster_concurrent_recoveries	i	D	"-1"	-1	
cluster.routing.allocation.disk.include_relocations	b	D	"true"		
cluster.routing.allocation.disk.reroute_interval	t	D	"60s"	0ms	
cluster.routing.allocation.disk.threshold_enabled	b	D	"true"		
cluster.routing.allocation.disk.warm_threshold_enabled	b	D	"true"		
cluster.routing.allocation.disk.watermark.flood_stage	r	D	"95%"		
cluster.routing.allocation.disk.watermark.high	r	D	"90%"		
cluster.routing.allocation.disk.watermark.low	r	D	"85%"		
cluster.routing.allocation.enable	x	D	"all"		
cluster.routing.allocation.load_awareness.allow_unassigned_primaries	b	D	"true"		
cluster.routing.allocation.load_awareness.flat_skew	i	D	"2"	2	
cluster.routing.allocation.load_awareness.provisioned_capacity	i	D	"-1"	-1	
cluster.routing.allocation.load_awareness.skew_factor	d	D	"50.0"	-1.0	
cluster.routing.allocation.move.primary_first	b	D	"false"		
cluster.routing.allocation.node_concurrent_incoming_recoveries	i	D	"2"	0	
cluster.routing.allocation.node_concurrent_outgoing_recoveries	i	D	"2"	0	
cluster.routing.allocation.node_concurrent_recoveries	i	D	"2"	0	
cluster.routing.allocation.node_initial_primaries_recoveries	i	D	"4"	0	
cluster.routing.allocation.node_initial_replicas_recoveries	i	D	"4"	0	
cluster.routing.allocation.primary_constraint.threshold	l	D	"10"	0	
cluster.routing.allocation.rebalance.primary.buffer	d	D	"0.1"	0.0	
cluster.routing.allocation.rebalance.primary.enable	b	D	"false"		
cluster.routing.allocation.remote_primary.ignore_throttle	b	D	"true"		
cluster.routing.allocation.same_shard.host	b	D	"false"		
cluster.routing.allocation.shard_movement_strategy	s	D	"no_preference"		
cluster.routing.allocation.shard_state.reroute.priority	s	D	"NORMAL"		
cluster.routing.allocation.shards_batch_gateway_allocator.primary_allocator_timeout	t	D	"20s"		
cluster.routing.allocation.shards_batch_gateway_allocator.replica_allocator_timeout	t	D	"20s"		
cluster.routing.allocation.shards_batch_gateway_allocator.schedule_reroute.priority	s	D	"NORMAL"		
cluster.routing.allocation.total_primary_shards_per_node	i	D	"-1"	-1	
cluster.routing.allocation.total_remote_capable_shards_limit	i	D	"-1"	-1	
cluster.routing.allocation.total_remote_capable_shards_per_node	i	D	"-1"	-1	
cluster.routing.allocation.total_shards_limit	i	D	"-1"	-1	
cluster.routing.allocation.total_shards_per_node	i	D	"-1"	-1	
cluster.routing.allocation.unassigned.node_left.delayed_timeout	t	D	"1m"	0ms	
cluster.routing.ignore_weighted_routing	b	D	"false"		
cluster.routing.rebalance.enable	x	D	"all"		
cluster.routing.search_replica.strict	b	D	"true"		
cluster.routing.use_adaptive_replica_selection	b	D	"true"		
cluster.routing.weighted.default_weight	d	D	"1.0"	1.0	
cluster.routing.weighted.fail_open	b	D	"true"		
cluster.routing.weighted.strict	b	D	"true"		
cluster.search.enabled_system_generated_factories	L	D	[]		
cluster.search.ignore_awareness_attributes	b	D	"true"		
cluster.search.request.slowlog.level	x	D	"TRACE"		
cluster.search.request.slowlog.threshold.debug	t	D	"-1"		
cluster.search.request.slowlog.threshold.info	t	D	"-1"		
cluster.search.request.slowlog.threshold.trace	t	D	"-1"		
cluster.search.request.slowlog.threshold.warn	t	D	"-1"		
cluster.service.slow_cluster_manager_task_logging_threshold	t	D	"10s"	0ms	
cluster.service.slow_task_logging_threshold	t	D	"30s"	0ms	
cluster.snapshot.info.max_concurrent_fetches	i	D	"5"	1	
cluster.task.consumers.top_n.frequency	t	D	"60s"	60s	
cluster.task.consumers.top_n.size	i	D	"10"	1	
cluster.tiering.filecache_active_threshold_percent	i	D	"90"	0	
cluster.tiering.jvm_usage_threshold_percent	i	D	"95"	0	
cluster.tiering.max_concurrent_hot_to_warm_requests	i	D	"200"	0	
cluster.tiering.max_concurrent_warm_to_hot_requests	i	D	"10"	0	
cluster.tiering.prepare_timeout	t	D	"90s"	30s	
cluster_manager.throttling.retry.base.delay	t	D	"5s"		
cluster_manager.throttling.retry.max.delay	t	D	"30s"		
gateway.slow_write_logging_threshold	t	D	"10s"	0ms	
http.request_id.max_length	i	D	"128"	16	
http.tracer.exclude	L	D	[]		
http.tracer.include	L	D	[]		
indices.breaker.fielddata.limit	p	D	"40%"		
indices.breaker.fielddata.overhead	d	D	"1.03"	0.0	
indices.breaker.request.limit	p	D	"60%"		
indices.breaker.request.overhead	d	D	"1.0"	0.0	
indices.breaker.total.limit	p	D	"95%"		
indices.composite_index.star_tree.enabled	b	D	"true"		
indices.composite_index.translog.max_flush_threshold_size	z	D	"512mb"		
indices.fielddata.cache.size	p	D	"35.0%"		
indices.id_field_data.enabled	b	D	"true"		
indices.mapping.dynamic_timeout	t	D	"30s"	0ms	
indices.mapping.max_in_flight_updates	i	D	"10"	1	
indices.publish_check_point.retry_timeout	t	D	"5m"		
indices.queries.cache.costly_min_frequency	i	D	"2"	1	
indices.queries.cache.min_frequency	i	D	"5"	1	
indices.queries.cache.skip_cache_factor	d	D	"10.0"	1.0	
indices.query.bool.max_clause_count	i	D	"1024"	1	
indices.recovery.chunk_size	z	D	"524272b"		
indices.recovery.internal_action_long_timeout	t	D	"1800000ms"	0s	
indices.recovery.internal_action_retry_timeout	t	D	"1m"	0ms	
indices.recovery.internal_action_timeout	t	D	"15m"	0ms	
indices.recovery.internal_remote_upload_timeout	t	D	"1h"		
indices.recovery.max_bytes_per_sec	z	D	"41943040b"		
indices.recovery.max_concurrent_file_chunks	i	D	"2"	1	
indices.recovery.max_concurrent_operations	i	D	"1"	1	
indices.recovery.max_concurrent_remote_store_streams	i	D	"4"	1	
indices.recovery.recovery_activity_timeout	t	D	"1800000ms"	0s	
indices.recovery.retry_delay_network	t	D	"5s"	0ms	
indices.recovery.retry_delay_state_sync	t	D	"500ms"	0ms	
indices.replication.initial_retry_backoff_bound	t	D	"50ms"	10ms	
indices.replication.max_bytes_per_sec	z	D	"-1b"		
indices.replication.merges.warmer.enabled	b	D	"false"		
indices.replication.merges.warmer.max_bytes_per_sec	z	D	"-1b"		
indices.replication.merges.warmer.min_segment_size_threshold	z	D	"524288000b"		
indices.replication.merges.warmer.timeout	t	D	"15m"	0m	
indices.replication.retry_timeout	t	D	"60s"		
indices.requests.cache.cleanup.staleness_threshold	r	D	"0%"		
indices.requests.cache.maximum_cacheable_size	i	D	"0"	0	
indices.requests.cache.tiered_spillover.disk.store.enabled	b	D	"true"		
indices.requests.cache.tiered_spillover.disk.store.policies.took_time.threshold	t	D	"10ms"	0ms	
indices.requests.cache.tiered_spillover.policies.took_time.threshold	t	D	"0ms"	0ms	
indices.translog_concurrent_recovery.batch_size	i	D	"500000"	1000	
indices.translog_concurrent_recovery.enable	b	D	"false"		
knn.algo_param.index_thread_qty	i	D	"1"		
knn.cache.item.expiry.enabled	b	D	"false"		
knn.cache.item.expiry.minutes	t	D	"3h"	0ms	
knn.circuit_breaker.triggered	b	D	"false"		
knn.circuit_breaker.unset.percentage	d	D	"75.0"	0.0	100.0
knn.feature.cache.force_evict.enabled	b	D	"false"		
knn.feature.prefetch.enabled	b	D	"true"		
knn.memory.circuit_breaker.enabled	b	D	"true"		
knn.memory.circuit_breaker.limit	p	D	"50%"		
knn.model.cache.size.limit	p	D	"10%"		
knn.model.index.number_of_replicas	i	D	"1"	0	
knn.model.index.number_of_shards	i	D	"1"	1	
knn.quantization.cache.expiry.minutes	t	D	"60m"	0ms	
knn.quantization.cache.size.limit	p	D	"5%"		
knn.remote_index_build.client.timeout	t	D	"60m"		
knn.remote_index_build.enabled	b	D	"false"		
knn.remote_index_build.poll.interval	t	D	"5s"		
knn.remote_index_build.repository	s	D	""		
knn.remote_index_build.service.endpoint	s	D	""		
knn.remote_index_build.size.max	z	D	"0b"		
knn.vector_streaming_memory.limit	p	D	"1%"		
ltr.breaker.enabled	b	D	"true"		
ltr.plugin.enabled	b	D	"true"		
monitor.fs.health.enabled	b	D	"true"		
monitor.fs.health.healthy_timeout_threshold	t	D	"60s"	1ms	
monitor.fs.health.slow_path_logging_threshold	t	D	"5s"	1ms	
network.breaker.inflight_requests.limit	p	D	"100%"		
network.breaker.inflight_requests.overhead	d	D	"2.0"	0.0	
node.auto_force_merge.cpu.threshold	d	D	"75.0"	10.0	100.0
node.auto_force_merge.disk.threshold	d	D	"85.0"	10.0	100.0
node.auto_force_merge.jvm.threshold	d	D	"75.0"	10.0	100.0
node.auto_force_merge.merge_delay	t	D	"15s"	1s	60s
node.auto_force_merge.scheduler.interval	t	D	"30m"	1s	24h
node.auto_force_merge.segment.count	i	D	"1"	1	
node.auto_force_merge.threads.concurrency_multiplier	i	D	"2"	2	
node.auto_force_merge.translog.age	t	D	"30m"	1s	24h
node.native_memory.buffer_percent	i	D	"0"	0	
node.native_memory.limit	z	D	"5855890636b"		
node.resource.tracker.global_cpu_usage.window_duration	t	D	"30s"	0ms	
node.resource.tracker.global_io_usage.window_duration	t	D	"120s"	0ms	
node.resource.tracker.global_jvmmp.window_duration	t	D	"30s"	0ms	
node.resource.tracker.global_native_memory_usage.window_duration	t	D	"30s"	0ms	
opendistro.alerting.action_throttle_max_value	t	D	"24h"	0ms	
opendistro.alerting.alert_backoff_count	i	D	"2"		
opendistro.alerting.alert_backoff_millis	t	D	"50ms"	0ms	
opendistro.alerting.alert_history_enabled	b	D	"true"		
opendistro.alerting.alert_history_max_age	t	D	"30d"	0ms	
opendistro.alerting.alert_history_max_docs	l	D	"1000"	0	
opendistro.alerting.alert_history_retention_period	t	D	"60d"	0ms	
opendistro.alerting.alert_history_rollover_period	t	D	"12h"	0ms	
opendistro.alerting.bulk_timeout	t	D	"120s"	0ms	
opendistro.alerting.destination.allow_list	L	D	["chime", "slack", "custom_webhook", "email", "test_action"]		
opendistro.alerting.filter_by_backend_roles	b	D	"false"		
opendistro.alerting.index_timeout	t	D	"60s"	0ms	
opendistro.alerting.input_timeout	t	D	"30s"	0ms	
opendistro.alerting.monitor.max_monitors	i	D	"1000"		
opendistro.alerting.move_alerts_backoff_count	i	D	"3"		
opendistro.alerting.move_alerts_backoff_millis	t	D	"250ms"	0ms	
opendistro.alerting.request_timeout	t	D	"10s"	0ms	
opendistro.anomaly_detection.ad_result_history_max_docs	l	D	"250000000"	0	
opendistro.anomaly_detection.ad_result_history_retention_period	t	D	"30d"	0ms	
opendistro.anomaly_detection.ad_result_history_rollover_period	t	D	"12h"	0ms	
opendistro.anomaly_detection.backoff_initial_delay	t	D	"1000ms"	0ms	
opendistro.anomaly_detection.backoff_minutes	t	D	"15m"	0ms	
opendistro.anomaly_detection.batch_task_piece_interval_seconds	i	D	"5"	1	
opendistro.anomaly_detection.batch_task_piece_size	i	D	"1000"	1	
opendistro.anomaly_detection.breaker.enabled	b	D	"true"		
opendistro.anomaly_detection.cooldown_minutes	t	D	"5m"	0ms	
opendistro.anomaly_detection.detection_interval	t	D	"10m"	0ms	
opendistro.anomaly_detection.detection_window_delay	t	D	"0m"		
opendistro.anomaly_detection.enabled	b	D	"true"		
opendistro.anomaly_detection.filter_by_backend_roles	b	D	"false"		
opendistro.anomaly_detection.index_pressure_soft_limit	d	D	"0.8"	0.0	
opendistro.anomaly_detection.max_anomaly_detectors	i	D	"1000"	0	
opendistro.anomaly_detection.max_anomaly_features	i	D	"5"	0	
opendistro.anomaly_detection.max_batch_task_per_node	i	D	"10"	1	
opendistro.anomaly_detection.max_cache_miss_handling_per_second	i	D	"100"	0	
opendistro.anomaly_detection.max_entities_for_preview	i	D	"30"	1	
opendistro.anomaly_detection.max_entities_per_query	i	D	"1000"	1	
opendistro.anomaly_detection.max_multi_entity_anomaly_detectors	i	D	"10"	0	
opendistro.anomaly_detection.max_old_ad_task_docs_per_detector	i	D	"1"	1	
opendistro.anomaly_detection.max_primary_shards	i	D	"10"	0	
opendistro.anomaly_detection.max_retry_for_backoff	i	D	"3"	0	
opendistro.anomaly_detection.max_retry_for_unresponsive_node	i	D	"5"	0	
opendistro.anomaly_detection.model_max_size_percent	d	D	"0.1"	0.0	0.7
opendistro.anomaly_detection.request_timeout	t	D	"60s"	0ms	
opendistro.asynchronous_search.max_keep_alive	t	D	"5d"	0ms	
opendistro.asynchronous_search.max_search_running_time	t	D	"12h"	0ms	
opendistro.asynchronous_search.max_wait_for_completion_timeout	t	D	"1m"	0ms	
opendistro.asynchronous_search.node_concurrent_running_searches	i	D	"20"	0	
opendistro.asynchronous_search.persist_search_failures	b	D	"false"		
opendistro.index_state_management.allow_list	L	D	["alias", "allocation", "close", "delete", "force_merge", "index_priority", "notification", "open", "read_only", "read_write", "replica_count", "rollup", "rollover", "search_only", "shrink", "snapshot", "transform", "stop_replication", "convert_index_to_remote"]		
opendistro.index_state_management.coordinator.backoff_count	i	D	"2"	0	
opendistro.index_state_management.coordinator.backoff_millis	t	D	"50ms"	0ms	
opendistro.index_state_management.coordinator.sweep_period	t	D	"10m"	5m	
opendistro.index_state_management.enabled	b	D	"true"		
opendistro.index_state_management.history.enabled	b	D	"true"		
opendistro.index_state_management.history.max_age	t	D	"24h"	0ms	
opendistro.index_state_management.history.max_docs	l	D	"2500000"	0	
opendistro.index_state_management.history.number_of_replicas	i	D	"1"		
opendistro.index_state_management.history.number_of_shards	i	D	"1"		
opendistro.index_state_management.history.rollover_check_period	t	D	"8h"	0ms	
opendistro.index_state_management.history.rollover_retention_period	t	D	"30d"	0ms	
opendistro.index_state_management.job_interval	i	D	"5"	1	
opendistro.index_state_management.restricted_index_pattern	s	D	"\\.opendistro_security|\\.kibana.*|\\.opendistro-ism-config"		
opendistro.index_state_management.snapshot.deny_list	L	D	[]		
opendistro.jobscheduler.jitter_limit	d	D	"0.6"	0.0	0.95
opendistro.jobscheduler.request_timeout	t	D	"10s"	0ms	
opendistro.jobscheduler.retry_count	i	D	"3"		
opendistro.jobscheduler.sweeper.backoff_millis	t	D	"50ms"	0ms	
opendistro.jobscheduler.sweeper.page_size	i	D	"100"		
opendistro.jobscheduler.sweeper.period	t	D	"5m"	0ms	
opendistro.rollup.dashboards.enabled	b	D	"true"		
opendistro.rollup.enabled	b	D	"true"		
opendistro.rollup.ingest.backoff_count	i	D	"5"		
opendistro.rollup.ingest.backoff_millis	t	D	"1000ms"	0ms	
opendistro.rollup.search.backoff_count	i	D	"5"		
opendistro.rollup.search.backoff_millis	t	D	"1000ms"	0ms	
opendistro.rollup.search.enabled	b	D	"true"		
opendistro.scheduled_jobs.enabled	b	D	"true"		
opendistro.scheduled_jobs.request_timeout	t	D	"10s"	0ms	
opendistro.scheduled_jobs.retry_count	i	D	"3"		
opendistro.scheduled_jobs.sweeper.backoff_millis	t	D	"50ms"	0ms	
opendistro.scheduled_jobs.sweeper.page_size	i	D	"100"		
opendistro.scheduled_jobs.sweeper.period	t	D	"5m"	0ms	
opendistro_security_config.ssl_dual_mode_enabled	b	D	"false"		
opensearch.notifications.core.allowed_config_types	L	D	["slack", "chime", "microsoft_teams", "webhook", "email", "sns", "ses_account", "smtp_account", "email_group"]		
opensearch.notifications.core.email.minimum_header_length	i	D	"160"		
opensearch.notifications.core.email.size_limit	i	D	"10000000"	10000	
opensearch.notifications.core.http.connection_timeout	i	D	"5000"		
opensearch.notifications.core.http.host_deny_list	L	D	[]		
opensearch.notifications.core.http.max_connection_per_route	i	D	"20"		
opensearch.notifications.core.http.max_connections	i	D	"60"		
opensearch.notifications.core.http.socket_timeout	i	D	"50000"		
opensearch.notifications.core.max_http_response_size	i	D	"104857600"		
opensearch.notifications.core.tooltip_support	b	D	"true"		
opensearch.notifications.general.default_items_query_count	i	D	"100"	10	
opensearch.notifications.general.filter_by_backend_roles	b	D	"false"		
opensearch.notifications.general.operation_timeout_ms	l	D	"60000"	100	
opensearch.observability.access.adminAccess	s	D	"AllObservabilityObjects"		
opensearch.observability.access.filterBy	s	D	"NoFilter"		
opensearch.observability.access.ignoreRoles	L	D	["own_index", "opensearch_dashboards_user", "notebooks_full_access", "notebooks_read_access"]		
opensearch.observability.general.defaultItemsQueryCount	i	D	"1000"	10	
opensearch.observability.general.operationTimeoutMs	l	D	"60000"	100	
opensearch.observability.polling.jobLockDurationSeconds	i	D	"300"	10	
opensearch.observability.polling.maxLockRetries	i	D	"4"	1	
opensearch.observability.polling.maxPollingDurationSeconds	i	D	"900"	300	
opensearch.observability.polling.minPollingDurationSeconds	i	D	"300"	60	
opensearch.reports.general.defaultItemsQueryCount	i	D	"100"	10	
opensearch.reports.general.operationTimeoutMs	l	D	"60000"	100	
plugins.alerting.action_throttle_max_value	t	D	"24h"	0ms	
plugins.alerting.alert_backoff_count	i	D	"2"		
plugins.alerting.alert_backoff_millis	t	D	"50ms"	0ms	
plugins.alerting.alert_finding_enabled	b	D	"true"		
plugins.alerting.alert_finding_max_docs	l	D	"1000"	0	
plugins.alerting.alert_finding_rollover_period	t	D	"12h"	0ms	
plugins.alerting.alert_findings_indexing_batch_size	i	D	"1000"	1	
plugins.alerting.alert_history_enabled	b	D	"true"		
plugins.alerting.alert_history_max_age	t	D	"30d"	0ms	
plugins.alerting.alert_history_max_docs	l	D	"1000"		
plugins.alerting.alert_history_retention_period	t	D	"60d"	0ms	
plugins.alerting.alert_history_rollover_period	t	D	"12h"	0ms	
plugins.alerting.bulk_timeout	t	D	"120s"	0ms	
plugins.alerting.comments_enabled	b	D	"true"		
plugins.alerting.comments_history_max_age	t	D	"30d"	0ms	
plugins.alerting.comments_history_max_docs	l	D	"1000"	0	
plugins.alerting.comments_history_retention_period	t	D	"60d"	0ms	
plugins.alerting.comments_history_rollover_period	t	D	"12h"	0ms	
plugins.alerting.cross_cluster_monitoring_enabled	b	D	"true"		
plugins.alerting.destination.allow_list	L	D	["chime", "slack", "custom_webhook", "email", "test_action"]		
plugins.alerting.external_scheduler.account_id	s	D	""		
plugins.alerting.external_scheduler.enabled	b	D	"false"		
plugins.alerting.external_scheduler.execution_role_name	s	D	""		
plugins.alerting.external_scheduler.job_queue_account_id	s	D	""		
plugins.alerting.external_scheduler.job_queue_message_group_key_name	s	D	""		
plugins.alerting.external_scheduler.job_queue_name	s	D	""		
plugins.alerting.external_scheduler.role_name	s	D	""		
plugins.alerting.filter_by_backend_roles	b	D	"false"		
plugins.alerting.finding_history_max_age	t	D	"30d"	0ms	
plugins.alerting.finding_history_retention_period	t	D	"60d"	0ms	
plugins.alerting.index_timeout	t	D	"60s"	0ms	
plugins.alerting.input_timeout	t	D	"30s"	0ms	
plugins.alerting.max_actionable_alert_count	l	D	"50"	-1	
plugins.alerting.max_comment_character_length	l	D	"2000"	0	
plugins.alerting.max_comments_per_alert	l	D	"500"	0	
plugins.alerting.max_comments_per_notification	i	D	"3"	0	
plugins.alerting.monitor.doc_level_monitor_execution_max_duration	t	D	"4m"	0ms	
plugins.alerting.monitor.doc_level_monitor_fan_out_nodes	i	D	"1000"	1	
plugins.alerting.monitor.doc_level_monitor_fanout_max_duration	t	D	"3m"	0ms	
plugins.alerting.monitor.doc_level_monitor_query_field_names_enabled	b	D	"true"		
plugins.alerting.monitor.doc_level_monitor_shard_fetch_size	i	D	"10000"	1	
plugins.alerting.monitor.max_monitors	i	D	"1000"		
plugins.alerting.monitor.max_ppl_triggers	i	D	"10"	0	
plugins.alerting.monitor.max_triggers	i	D	"10"	0	
plugins.alerting.monitor.percolate_query_docs_size_memory_percentage_limit	i	D	"10"	0	
plugins.alerting.monitor.percolate_query_max_num_docs_in_memory	i	D	"50000"	1000	
plugins.alerting.move_alerts_backoff_count	i	D	"3"		
plugins.alerting.move_alerts_backoff_millis	t	D	"250ms"	0ms	
plugins.alerting.multi_tenant_trigger_eval_enabled	b	D	"false"		
plugins.alerting.notification_context_results_allowed_roles	L	D	[]		
plugins.alerting.notification_message_source_max_length	i	D	"3000"	1000	
plugins.alerting.notification_subject_source_max_length	i	D	"1000"	100	
plugins.alerting.ppl_monitor_max_query_length	l	D	"2000"	0	
plugins.alerting.ppl_query_max_execution_duration	t	D	"30s"	0ms	
plugins.alerting.ppl_query_results_max_datarows	l	D	"10000"	1	
plugins.alerting.ppl_query_results_max_size	l	D	"3000"	0	
plugins.alerting.request_timeout	t	D	"10s"	0ms	
plugins.alerting.tenant.account_id_header	s	D	""		
plugins.anomaly_detection.ad_result_history_max_docs_per_shard	l	D	"1350000000"	0	
plugins.anomaly_detection.ad_result_history_retention_period	t	D	"30d"	0ms	
plugins.anomaly_detection.ad_result_history_rollover_period	t	D	"12h"	0ms	
plugins.anomaly_detection.backoff_initial_delay	t	D	"1000ms"	0ms	
plugins.anomaly_detection.backoff_minutes	t	D	"15m"	0ms	
plugins.anomaly_detection.batch_task_piece_interval_seconds	i	D	"5"	1	
plugins.anomaly_detection.batch_task_piece_size	i	D	"1000"	1	
plugins.anomaly_detection.breaker.enabled	b	D	"true"		
plugins.anomaly_detection.category_field_limit	i	D	"2"	0	
plugins.anomaly_detection.checkpoint_maintain_queue_max_heap_percent	d	D	"0.001"	0.0	
plugins.anomaly_detection.checkpoint_read_queue_batch_size	i	D	"25"	1	
plugins.anomaly_detection.checkpoint_read_queue_concurrency	i	D	"1"	1	
plugins.anomaly_detection.checkpoint_read_queue_max_heap_percent	d	D	"0.001"	0.0	
plugins.anomaly_detection.checkpoint_saving_freq	t	D	"12h"	0ms	
plugins.anomaly_detection.checkpoint_ttl	t	D	"7d"	0ms	
plugins.anomaly_detection.checkpoint_write_queue_batch_size	i	D	"25"	1	
plugins.anomaly_detection.checkpoint_write_queue_concurrency	i	D	"2"	1	
plugins.anomaly_detection.checkpoint_write_queue_max_heap_percent	d	D	"0.01"	0.0	
plugins.anomaly_detection.cold_entity_queue_max_heap_percent	d	D	"0.001"	0.0	
plugins.anomaly_detection.cooldown_minutes	t	D	"5m"	0ms	
plugins.anomaly_detection.dedicated_cache_size	i	D	"10"	0	
plugins.anomaly_detection.delete_anomaly_result_when_delete_detector	b	D	"false"		
plugins.anomaly_detection.detection_interval	t	D	"10m"	0ms	
plugins.anomaly_detection.detection_window_delay	t	D	"0m"		
plugins.anomaly_detection.door_keeper_in_cache.enabled	b	D	"false"		
plugins.anomaly_detection.enabled	b	D	"true"		
plugins.anomaly_detection.entity_cold_start_queue_concurrency	i	D	"1"	1	
plugins.anomaly_detection.entity_cold_start_queue_max_heap_percent	d	D	"0.001"	0.0	
plugins.anomaly_detection.expected_checkpoint_maintain_time_in_millisecs	i	D	"1000"	0	
plugins.anomaly_detection.expected_cold_entity_execution_time_in_millisecs	i	D	"3000"	0	
plugins.anomaly_detection.filter_by_backend_roles	b	D	"false"		
plugins.anomaly_detection.hcad_cold_start_interpolation.enabled	b	D	"false"		
plugins.anomaly_detection.index_pressure_hard_limit	d	D	"0.9"	0.0	
plugins.anomaly_detection.index_pressure_soft_limit	d	D	"0.6"	0.0	
plugins.anomaly_detection.insights_enabled	b	D	"false"		
plugins.anomaly_detection.jvm_heap_usage_threshold	i	D	"95"	0	
plugins.anomaly_detection.max_anomaly_detectors	i	D	"1000"	0	
plugins.anomaly_detection.max_anomaly_features	i	D	"5"	0	
plugins.anomaly_detection.max_batch_task_per_node	i	D	"10"	1	
plugins.anomaly_detection.max_cached_deleted_tasks	i	D	"1000"	1	
plugins.anomaly_detection.max_concurrent_preview	i	D	"2"	1	
plugins.anomaly_detection.max_entities_for_preview	i	D	"5"	1	
plugins.anomaly_detection.max_entities_per_query	i	D	"1000000"	0	
plugins.anomaly_detection.max_model_size_per_node	i	D	"100"	1	
plugins.anomaly_detection.max_multi_entity_anomaly_detectors	i	D	"10"	0	
plugins.anomaly_detection.max_old_ad_task_docs_per_detector	i	D	"1"	1	
plugins.anomaly_detection.max_primary_shards	i	D	"10"	0	
plugins.anomaly_detection.max_retry_for_backoff	i	D	"3"	0	
plugins.anomaly_detection.max_retry_for_unresponsive_node	i	D	"5"	0	
plugins.anomaly_detection.max_running_entities_per_detector_for_historical_analysis	i	D	"10"	1	
plugins.anomaly_detection.max_top_entities_for_historical_analysis	i	D	"1000"	1	
plugins.anomaly_detection.model_max_size_percent	d	D	"0.1"	0.0	0.9
plugins.anomaly_detection.page_size	i	D	"1000"	0	
plugins.anomaly_detection.request_timeout	t	D	"60s"	0ms	
plugins.anomaly_detection.result_write_queue_batch_size	i	D	"5000"	1	
plugins.anomaly_detection.result_write_queue_concurrency	i	D	"2"	1	
plugins.anomaly_detection.result_write_queue_max_heap_percent	d	D	"0.01"	0.0	
plugins.asynchronous_search.max_keep_alive	t	D	"5d"	0ms	
plugins.asynchronous_search.max_search_running_time	t	D	"12h"	0ms	
plugins.asynchronous_search.max_wait_for_completion_timeout	t	D	"1m"	0ms	
plugins.asynchronous_search.node_concurrent_running_searches	i	D	"20"	0	
plugins.asynchronous_search.persist_search_failures	b	D	"false"		
plugins.calcite.all_join_types.allowed	b	D	"false"		
plugins.calcite.enabled	b	D	"true"		
plugins.calcite.fallback.allowed	b	D	"false"		
plugins.calcite.pushdown.enabled	b	D	"true"		
plugins.calcite.pushdown.rowcount.estimation.factor	d	D	"0.9"	4.9E-324	
plugins.flow_framework.enabled	b	D	"true"		
plugins.flow_framework.filter_by_backend_roles	b	D	"false"		
plugins.flow_framework.max_active_deprovisions_per_tenant	i	D	"1"	1	
plugins.flow_framework.max_active_provisions_per_tenant	i	D	"2"	1	
plugins.flow_framework.max_workflow_steps	i	D	"50"	1	
plugins.flow_framework.max_workflows	i	D	"1000"	0	
plugins.flow_framework.request_timeout	t	D	"10s"	0ms	
plugins.flow_framework.task_request_retry_duration	t	D	"5s"	0ms	
plugins.forecast.backoff_initial_delay	t	D	"1000ms"	0ms	
plugins.forecast.backoff_minutes	t	D	"15m"	0ms	
plugins.forecast.category_field_limit	i	D	"2"	0	
plugins.forecast.checkpoint_maintain_queue_max_heap_percent	d	D	"0.001"	0.0	
plugins.forecast.checkpoint_read_queue_batch_size	i	D	"25"	1	
plugins.forecast.checkpoint_read_queue_concurrency	i	D	"1"	1	
plugins.forecast.checkpoint_read_queue_max_heap_percent	d	D	"0.001"	0.0	
plugins.forecast.checkpoint_saving_freq	t	D	"12h"	0ms	
plugins.forecast.checkpoint_ttl	t	D	"7d"	0ms	
plugins.forecast.checkpoint_write_queue_batch_size	i	D	"25"	1	
plugins.forecast.checkpoint_write_queue_concurrency	i	D	"2"	1	
plugins.forecast.checkpoint_write_queue_max_heap_percent	d	D	"0.01"	0.0	
plugins.forecast.cold_entity_queue_max_heap_percent	d	D	"0.001"	0.0	
plugins.forecast.cold_start_queue_concurrency	i	D	"1"	1	
plugins.forecast.cold_start_queue_max_heap_percent	d	D	"0.001"	0.0	
plugins.forecast.dedicated_cache_size	i	D	"10"	0	
plugins.forecast.default_interval	t	D	"10m"	0ms	
plugins.forecast.default_window_delay	t	D	"0m"		
plugins.forecast.delete_forecast_result_when_delete_forecaster	b	D	"false"		
plugins.forecast.enabled	b	D	"true"		
plugins.forecast.expected_checkpoint_maintain_time_in_millisecs	i	D	"1000"	0	
plugins.forecast.expected_cold_entity_execution_time_in_millisecs	i	D	"3000"	0	
plugins.forecast.filter_by_backend_roles	b	D	"false"		
plugins.forecast.forecast_result_history_max_docs_per_shard	l	D	"1350000000"	0	
plugins.forecast.forecast_result_history_retention_period	t	D	"30d"	0ms	
plugins.forecast.forecast_result_history_rollover_period	t	D	"12h"	0ms	
plugins.forecast.index_pressure_hard_limit	d	D	"0.9"	0.0	
plugins.forecast.index_pressure_soft_limit	d	D	"0.6"	0.0	
plugins.forecast.max_entities_per_interval	i	D	"1000000"	0	
plugins.forecast.max_forecasters	i	D	"1000"	0	
plugins.forecast.max_hc_forecasters	i	D	"10"	0	
plugins.forecast.max_model_size_per_node	i	D	"100"	1	
plugins.forecast.max_old_task_docs_per_forecaster	i	D	"1"	1	
plugins.forecast.max_primary_shards	i	D	"10"	0	
plugins.forecast.max_retry_for_backoff	i	D	"3"	0	
plugins.forecast.model_max_size_percent	d	D	"0.1"	0.0	0.9
plugins.forecast.page_size	i	D	"1000"	0	
plugins.forecast.request_timeout	t	D	"10s"	0ms	
plugins.forecast.result_write_queue_batch_size	i	D	"5000"	1	
plugins.forecast.result_write_queue_concurrency	i	D	"2"	1	
plugins.forecast.result_write_queue_max_heap_percent	d	D	"0.01"	0.0	
plugins.geospatial.geojson.max_coordinates_per_geo	i	D	"10000"		
plugins.geospatial.geojson.max_geometry_collection_nested_depth	i	D	"5"		
plugins.geospatial.geojson.max_holes_per_polygon	i	D	"1000"		
plugins.geospatial.geojson.max_multi_geometries	i	D	"100"		
plugins.geospatial.ip2geo.datasource.batch_size	i	D	"10000"	1	
plugins.geospatial.ip2geo.datasource.endpoint	s	D	"https://geoip.maps.opensearch.org/v1/geolite2-city/manifest.json"		
plugins.geospatial.ip2geo.datasource.endpoint.denylist	L	D	["127.0.0.0/8", "169.254.0.0/16", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "0.0.0.0/8", "100.64.0.0/10", "192.0.0.0/24", "192.0.2.0/24", "198.18.0.0/15", "192.88.99.0/24", "198.51.100.0/24", "203.0.113.0/24", "224.0.0.0/4", "240.0.0.0/4", "255.255.255.255/32", "::1/128", "fe80::/10", "fc00::/7", "::/128", "2001:db8::/32", "ff00::/8"]		
plugins.geospatial.ip2geo.datasource.update_interval_in_days	l	D	"3"	1	
plugins.geospatial.ip2geo.processor.cache_size	l	D	"1000"	0	
plugins.geospatial.ip2geo.timeout	t	D	"30s"	1s	
plugins.index_management.filter_by_backend_roles	b	D	"false"		
plugins.index_state_management.action_validation.enabled	b	D	"false"		
plugins.index_state_management.allow_list	L	D	["alias", "allocation", "close", "delete", "force_merge", "index_priority", "notification", "open", "read_only", "read_write", "replica_count", "rollup", "rollover", "search_only", "shrink", "snapshot", "transform", "stop_replication", "convert_index_to_remote"]		
plugins.index_state_management.coordinator.backoff_count	i	D	"2"	0	
plugins.index_state_management.coordinator.backoff_millis	t	D	"50ms"	0ms	
plugins.index_state_management.coordinator.sweep_period	t	D	"10m"	5m	
plugins.index_state_management.coordinator.sweep_skip_period	t	D	"5m"		
plugins.index_state_management.enabled	b	D	"true"		
plugins.index_state_management.history.enabled	b	D	"true"		
plugins.index_state_management.history.max_age	t	D	"24h"	0ms	
plugins.index_state_management.history.max_docs	l	D	"2500000"	0	
plugins.index_state_management.history.number_of_replicas	i	D	"1"		
plugins.index_state_management.history.number_of_shards	i	D	"1"		
plugins.index_state_management.history.rollover_check_period	t	D	"8h"	0ms	
plugins.index_state_management.history.rollover_retention_period	t	D	"30d"	0ms	
plugins.index_state_management.jitter	d	D	"0.6"	0.0	1.0
plugins.index_state_management.job_interval	i	D	"5"	1	
plugins.index_state_management.restricted_index_pattern	s	D	"\\.opendistro_security|\\.kibana.*|\\.opendistro-ism-config"		
plugins.index_state_management.snapshot.deny_list	L	D	[]		
plugins.jobscheduler.history.enabled	b	D	"false"		
plugins.jobscheduler.jitter_limit	d	D	"0.6"	4.9E-324	
plugins.jobscheduler.request_timeout	t	D	"10s"	0ms	
plugins.jobscheduler.retry_count	i	D	"3"		
plugins.jobscheduler.sweeper.backoff_millis	t	D	"50ms"	0ms	
plugins.jobscheduler.sweeper.page_size	i	D	"100"		
plugins.jobscheduler.sweeper.period	t	D	"5m"	0ms	
plugins.ml_commons.ag_ui_enabled	b	D	"false"		
plugins.ml_commons.agent_framework_enabled	b	D	"true"		
plugins.ml_commons.agentic_memory_enabled	b	D	"true"		
plugins.ml_commons.allow_custom_deployment_plan	b	D	"false"		
plugins.ml_commons.allow_registering_model_via_local_file	b	D	"false"		
plugins.ml_commons.allow_registering_model_via_url	b	D	"false"		
plugins.ml_commons.batch_ingestion_bulk_size	i	D	"500"	100	
plugins.ml_commons.connector.private_ip_enabled	b	D	"false"		
plugins.ml_commons.connector_access_control_enabled	b	D	"false"		
plugins.ml_commons.controller_enabled	b	D	"true"		
plugins.ml_commons.disk_free_space_threshold	z	D	"5368709120b"		
plugins.ml_commons.enable_inhouse_python_model	b	D	"false"		
plugins.ml_commons.exclude_nodes._name	s	D	""		
plugins.ml_commons.execute_tools_enabled	b	D	"true"		
plugins.ml_commons.index_insight_feature_enabled	b	D	"false"		
plugins.ml_commons.jvm_heap_memory_threshold	i	D	"85"	0	
plugins.ml_commons.local_model.enabled	b	D	"true"		
plugins.ml_commons.max_batch_inference_tasks	i	D	"100"	0	
plugins.ml_commons.max_batch_ingestion_tasks	i	D	"100"	0	
plugins.ml_commons.max_deploy_model_tasks_per_node	i	D	"10"	0	
plugins.ml_commons.max_json_size	i	D	"100000000"	-1	
plugins.ml_commons.max_ml_task_per_node	i	D	"10"	0	
plugins.ml_commons.max_model_on_node	i	D	"10"	0	
plugins.ml_commons.max_register_model_tasks_per_node	i	D	"10"	0	
plugins.ml_commons.mcp_connector_enabled	b	D	"false"		
plugins.ml_commons.mcp_header_passthrough_enabled	b	D	"false"		
plugins.ml_commons.mcp_server_enabled	b	D	"false"		
plugins.ml_commons.memory.default_history_max_count	i	D	"-1"	-1	
plugins.ml_commons.memory.default_long_term_max_count	i	D	"-1"	-1	
plugins.ml_commons.memory.default_session_max_count	i	D	"-1"	-1	
plugins.ml_commons.memory.default_session_retention_days	i	D	"-1"	-1	
plugins.ml_commons.memory.orphan_ttl_days	i	D	"7"	1	
plugins.ml_commons.memory.retention_enabled	b	D	"false"		
plugins.ml_commons.memory.retention_job_interval_hours	i	D	"24"	1	
plugins.ml_commons.memory.retention_job_throttle_seconds	i	D	"5"	1	
plugins.ml_commons.memory.working_memory_ttl_days	i	D	"-1"	-1	
plugins.ml_commons.memory_feature_enabled	b	D	"true"		
plugins.ml_commons.metrics_static_collection_enabled	b	D	"false"		
plugins.ml_commons.ml_task_timeout_in_seconds	i	D	"600"	1	
plugins.ml_commons.model_access_control_enabled	b	D	"false"		
plugins.ml_commons.model_auto_deploy.enable	b	D	"true"		
plugins.ml_commons.model_auto_redeploy.enable	b	D	"true"		
plugins.ml_commons.model_auto_redeploy.lifetime_retry_times	i	D	"3"		
plugins.ml_commons.model_auto_redeploy_success_ratio	d	D	"0.8"	0.0	1.0
plugins.ml_commons.monitoring_request_count	l	D	"100"	0	10000000
plugins.ml_commons.native_memory_threshold	i	D	"90"	0	
plugins.ml_commons.offline_batch_inference_enabled	b	D	"true"		
plugins.ml_commons.offline_batch_ingestion_enabled	b	D	"true"		
plugins.ml_commons.only_run_on_ml_node	b	D	"true"		
plugins.ml_commons.rag_pipeline_feature_enabled	b	D	"true"		
plugins.ml_commons.remote_agentic_memory_enabled	b	D	"false"		
plugins.ml_commons.remote_inference.enabled	b	D	"true"		
plugins.ml_commons.remote_job.status_field	L	D	["status", "Status", "TransformJobStatus"]		
plugins.ml_commons.remote_job.status_regex.cancelled	s	D	"(stopped|cancelled)"		
plugins.ml_commons.remote_job.status_regex.cancelling	s	D	"(stopping|cancelling)"		
plugins.ml_commons.remote_job.status_regex.completed	s	D	"(complete|completed|partiallyCompleted)"		
plugins.ml_commons.remote_job.status_regex.expired	s	D	"(expired|timeout)"		
plugins.ml_commons.remote_job.status_regex.failed	s	D	"(failed)"		
plugins.ml_commons.safe_delete_model	b	D	"false"		
plugins.ml_commons.stream_enabled	b	D	"false"		
plugins.ml_commons.sync_up_job_interval_in_seconds	i	D	"10"	0	
plugins.ml_commons.task_dispatch_policy	s	D	"round_robin"		
plugins.ml_commons.task_dispatcher.eligible_node_role.local_model	L	D	["data", "ml"]		
plugins.ml_commons.task_dispatcher.eligible_node_role.remote_model	L	D	["data", "ml"]		
plugins.ml_commons.trusted_connector_endpoints_regex	L	D	["^https://runtime\\.sagemaker\\..*[a-z0-9-]\\.amazonaws\\.com/.*$", "^https://api\\.sagemaker\\..*[a-z0-9-]\\.amazonaws\\.com/.*$", "^https://api\\.openai\\.com/.*$", "^https://api\\.cohere\\.ai/.*$", "^https://api\\.deepseek\\.com/.*$", "^https://generativelanguage\\.googleapis\\.com/.*$", "^https://bedrock-runtime\\..*[a-z0-9-]\\.amazonaws\\.com/.*$", "^https://bedrock-agent-runtime\\..*[a-z0-9-]\\.amazonaws\\.com/.*$", "^https://bedrock\\..*[a-z0-9-]\\.amazonaws\\.com/.*$", "^https://textract\\..*[a-z0-9-]\\.amazonaws\\.com$", "^https://comprehend\\..*[a-z0-9-]\\.amazonaws\\.com$", "^https://rekognition(-fips)?\\..*[a-z0-9-]\\.amazonaws\\.com$"]		
plugins.ml_commons.trusted_connector_private_endpoints_regex	L	D	[]		
plugins.ml_commons.trusted_url_regex	s	D	"^(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]"		
plugins.ml_commons.unified_agent_api_enabled	b	D	"false"		
plugins.neural_search.circuit_breaker.limit	p	D	"10%"		
plugins.neural_search.circuit_breaker.overhead	d	D	"1.0"	0.0	
plugins.neural_search.sparse.algo_param.index_thread_qty	i	D	"1"	1	
plugins.neural_search.stats_enabled	b	D	"false"		
plugins.ppl.enabled	b	D	"true"		
plugins.ppl.join.subsearch_maxout	i	D	"50000"		
plugins.ppl.pattern.buffer.limit	i	D	"100000"	50000	
plugins.ppl.pattern.max.sample.count	i	D	"10"	0	
plugins.ppl.pattern.method	s	D	"SIMPLE_PATTERN"		
plugins.ppl.pattern.mode	s	D	"LABEL"		
plugins.ppl.pattern.show.numbered.token	b	D	"false"		
plugins.ppl.query.timeout	t	D	"300s"	0ms	
plugins.ppl.rex.max_match.limit	i	D	"10"	1	
plugins.ppl.subsearch.maxout	i	D	"10000"		
plugins.ppl.syntax.legacy.preferred	b	D	"true"		
plugins.ppl.values.max.limit	i	D	"0"	-1	
plugins.query.buckets	i	D	"10000"	0	
plugins.query.datasources.enabled	b	D	"true"		
plugins.query.datasources.limit	i	D	"20"		
plugins.query.datasources.uri.hosts.denylist	L	D	[]		
plugins.query.executionengine.async_query.enabled	b	D	"true"		
plugins.query.executionengine.async_query.external_scheduler.enabled	b	D	"true"		
plugins.query.executionengine.async_query.external_scheduler.interval	s	D	""		
plugins.query.executionengine.spark.auto_index_management.enabled	b	D	"true"		
plugins.query.executionengine.spark.config	s	D	""		
plugins.query.executionengine.spark.refresh_job.limit	i	D	"5"		
plugins.query.executionengine.spark.result.index.ttl	t	D	"60d"	0ms	
plugins.query.executionengine.spark.session.index.ttl	t	D	"30d"	0ms	
plugins.query.executionengine.spark.session.limit	i	D	"10"		
plugins.query.executionengine.spark.session_inactivity_timeout_millis	l	D	"180000"		
plugins.query.executionengine.spark.streamingjobs.housekeeper.interval	t	D	"15m"	0ms	
plugins.query.field_type_tolerance	b	D	"true"		
plugins.query.max_expression_depth	i	D	"1000"	0	
plugins.query.memory_limit	p	D	"85%"		
plugins.query.metrics.rolling_interval	l	D	"60"	1	
plugins.query.metrics.rolling_window	l	D	"3600"	2	
plugins.query.size_limit	i	D	"10000"	0	
plugins.replication.autofollow.concurrent_replication_jobs_trigger_size	i	D	"3"	1	
plugins.replication.autofollow.fetch_poll_interval	t	D	"30s"	30s	1h
plugins.replication.autofollow.retry_poll_interval	t	D	"1h"	1m	4h
plugins.replication.follower.block.start	b	D	"false"		
plugins.replication.follower.bulk_batch_size	i	D	"10"	1	
plugins.replication.follower.bulk_poll_timeout	i	D	"15"	1	
plugins.replication.follower.concurrent_readers_per_shard	i	D	"2"	1	
plugins.replication.follower.concurrent_writers_per_shard	i	D	"2"	1	
plugins.replication.follower.index.ops_batch_size	i	D	"50000"	16	
plugins.replication.follower.index.recovery.chunk_size	z	D	"10mb"		
plugins.replication.follower.index.recovery.max_concurrent_file_chunks	i	D	"5"	1	
plugins.replication.follower.metadata_sync_interval	t	D	"60s"	5s	
plugins.replication.follower.poll_interval	t	D	"50ms"	1ms	1s
plugins.replication.follower.retention_lease_max_failure_duration	t	D	"1h"	1s	12h
plugins.replication.leader.thread_pool.queue_size	i	D	"1000"	0	
plugins.replication.leader.thread_pool.size	i	D	"0"	0	
plugins.replication.replicate.delete_index	b	D	"false"		
plugins.rollup.dashboards.enabled	b	D	"true"		
plugins.rollup.enabled	b	D	"true"		
plugins.rollup.ingest.backoff_count	i	D	"5"		
plugins.rollup.ingest.backoff_millis	t	D	"1000ms"	0ms	
plugins.rollup.search.backoff_count	i	D	"5"		
plugins.rollup.search.backoff_millis	t	D	"1000ms"	0ms	
plugins.rollup.search.enabled	b	D	"true"		
plugins.rollup.search.search_all_jobs	b	D	"false"		
plugins.rollup.search.search_source_indices	b	D	"false"		
plugins.scheduled_jobs.enabled	b	D	"true"		
plugins.scheduled_jobs.request_timeout	t	D	"10s"	0ms	
plugins.scheduled_jobs.retry_count	i	D	"3"		
plugins.scheduled_jobs.sweeper.backoff_millis	t	D	"50ms"	0ms	
plugins.scheduled_jobs.sweeper.page_size	i	D	"100"		
plugins.scheduled_jobs.sweeper.period	t	D	"5m"	0ms	
plugins.search_relevance.query_set.maximum	i	D	"1000"		
plugins.search_relevance.scheduled_experiments_enabled	b	D	"true"		
plugins.search_relevance.scheduled_experiments_minimum_interval	t	D	"1s"	0ms	
plugins.search_relevance.scheduled_experiments_timeout	t	D	"60m"	0ms	
plugins.search_relevance.stats_enabled	b	D	"true"		
plugins.search_relevance.workbench_enabled	b	D	"true"		
plugins.security.cache.ttl_minutes	i	D	"60"	0	
plugins.security.dls.write_blocked	b	D	"false"		
plugins.security.experimental.resource_sharing.enabled	b	D	"false"		
plugins.security.experimental.resource_sharing.protected_types	L	D	[]		
plugins.security.unsupported.passive_intertransport_auth_initially	b	D	"false"		
plugins.security.user_attribute_serialization.enabled	b	D	"false"		
plugins.security_analytics.action_throttle_max_value	t	D	"24h"	0ms	
plugins.security_analytics.alert_finding_enabled	b	D	"true"		
plugins.security_analytics.alert_finding_max_docs	l	D	"1000"	0	
plugins.security_analytics.alert_finding_rollover_period	t	D	"12h"	0ms	
plugins.security_analytics.alert_history_enabled	b	D	"true"		
plugins.security_analytics.alert_history_max_age	t	D	"30d"	0ms	
plugins.security_analytics.alert_history_max_docs	l	D	"1000"	0	
plugins.security_analytics.alert_history_retention_period	t	D	"60d"	0ms	
plugins.security_analytics.alert_history_rollover_period	t	D	"12h"	0ms	
plugins.security_analytics.auto_correlations_enabled	b	D	"false"		
plugins.security_analytics.correlation_history_max_age	t	D	"30d"	0ms	
plugins.security_analytics.correlation_history_max_docs	l	D	"1000"	0	
plugins.security_analytics.correlation_history_retention_period	t	D	"60d"	0ms	
plugins.security_analytics.correlation_history_rollover_period	t	D	"12h"	0ms	
plugins.security_analytics.correlation_time_window	t	D	"5m"	0ms	
plugins.security_analytics.enable_detectors_with_dedicated_query_indices	b	D	"true"		
plugins.security_analytics.enable_workflow_usage	b	D	"true"		
plugins.security_analytics.filter_by_backend_roles	b	D	"false"		
plugins.security_analytics.finding_history_max_age	t	D	"30d"	0ms	
plugins.security_analytics.finding_history_retention_period	t	D	"60d"	0ms	
plugins.security_analytics.index_timeout	t	D	"60s"	0ms	
plugins.security_analytics.ioc.index_retention_period	t	D	"30d"	1d	
plugins.security_analytics.ioc.max_indices_per_alias	i	D	"2"	1	
plugins.security_analytics.ioc.scan_max_terms_count	i	D	"65536"	1	
plugins.security_analytics.ioc_finding_enabled	b	D	"true"		
plugins.security_analytics.ioc_finding_history_max_age	t	D	"30d"	0ms	
plugins.security_analytics.ioc_finding_history_max_docs	l	D	"1000"	0	
plugins.security_analytics.ioc_finding_history_retention_period	t	D	"60d"	0ms	
plugins.security_analytics.ioc_finding_history_rollover_period	t	D	"12h"	0ms	
plugins.security_analytics.mappings.default_schema	s	D	"ecs"		
plugins.security_analytics.request_timeout	t	D	"10s"	0ms	
plugins.security_analytics.threat_intel_timeout	t	D	"30s"	1s	
plugins.security_analytics.threatintel.tifjob.batch_size	i	D	"10000"	1	
plugins.security_analytics.threatintel.tifjob.update_interval	t	D	"1440m"		
plugins.security_config.ssl_dual_mode_enabled	b	D	"false"		
plugins.snapshot_management.filter_by_backend_roles	b	D	"false"		
plugins.sql.cursor.keep_alive	t	D	"1m"	0ms	
plugins.sql.enabled	b	D	"true"		
plugins.sql.slowlog	i	D	"2"	0	
plugins.timeseries.backoff_minutes	t	D	"15m"	0ms	
plugins.timeseries.breaker.enabled	b	D	"true"		
plugins.timeseries.cooldown_minutes	t	D	"5m"	0ms	
plugins.timeseries.max_cached_deleted_tasks	i	D	"1000"	1	
plugins.timeseries.max_retry_for_unresponsive_node	i	D	"5"	0	
plugins.transform.circuit_breaker.enabled	b	D	"true"		
plugins.transform.circuit_breaker.jvm.threshold	i	D	"85"	0	
plugins.transform.internal.index.backoff_count	i	D	"5"		
plugins.transform.internal.index.backoff_millis	t	D	"1000ms"	0ms	
plugins.transform.internal.search.backoff_count	i	D	"5"		
plugins.transform.internal.search.backoff_millis	t	D	"1000ms"	0ms	
point_in_time.max_keep_alive	t	D	"24h"	0ms	
reindex.remote.retry.initial_backoff	t	D	"500ms"	50ms	5000ms
reindex.remote.retry.max_count	i	D	"15"	1	
remote_store.moving_average_window_size	i	D	"20"	5	
remote_store.segment.pressure.bytes_lag.variance_factor	d	D	"10.0"	1.0	
remote_store.segment.pressure.consecutive_failures.limit	i	D	"5"	1	
remote_store.segment.pressure.enabled	b	D	"true"		
remote_store.segment.pressure.time_lag.variance_factor	d	D	"10.0"	1.0	
script.max_compilations_rate	x	D	"use-context"		
script.max_size_in_bytes	i	D	"65535"	0	
search.aggregation.bucket_selection_strategy_factor	i	D	"5"	0	
search.aggregation_rewrite_filters.segment_threshold.docs_per_bucket	i	D	"1000"	0	
search.aggregations.cardinality.hybrid_collector.enabled	b	D	"true"		
search.aggregations.cardinality.hybrid_collector.memory_threshold	p	D	"1%"		
search.aggregations.streaming.max_estimated_bucket_count	l	D	"100000"	1	
search.aggregations.streaming.min_cardinality_ratio	d	D	"0.01"	0.0	1.0
search.aggregations.streaming.min_estimated_bucket_count	l	D	"1000"	1	
search.aggregations.terms.max_precompute_cardinality	l	D	"30000"	0	
search.allow_expensive_queries	b	D	"true"		
search.cancel_after_time_interval	t	D	"-1"		
search.concurrent.max_slice_count	i	D	"4"	0	
search.concurrent_segment_search.enabled	b	D	"false"		
search.concurrent_segment_search.mode	x	D	"auto"		
search.concurrent_segment_search.partition_min_segment_size	i	D	"500000"	1000	
search.concurrent_segment_search.partition_strategy	x	D	"balanced"		
search.default_allow_partial_results	b	D	"true"		
search.default_keep_alive	t	D	"5m"	0ms	
search.default_search_timeout	t	D	"-1"		
search.derived_field.enabled	b	D	"true"		
search.dynamic_pruning.cardinality_aggregation.max_allowed_cardinality	i	D	"100"	0	
search.index_pruning.enabled	b	D	"false"		
search.index_pruning.fields	L	D	[]		
search.index_pruning.min_shards	i	D	"128"	1	
search.insights.live_queries.cache.idle_timeout	t	D	"5m"	0ms	
search.insights.recommendations.enabled	b	D	"true"		
search.insights.recommendations.enabled_rules	L	D	[]		
search.insights.recommendations.max_count	i	D	"10"	1	
search.insights.recommendations.min_confidence	d	D	"0.5"	0.0	1.0
search.insights.top_queries.cpu.enabled	b	D	"true"		
search.insights.top_queries.cpu.top_n_size	i	D	"10"	1	
search.insights.top_queries.cpu.window_size	t	D	"5m"	1m	
search.insights.top_queries.excluded_indices	L	D	[]		
search.insights.top_queries.exporter.delete_after_days	i	D	"7"	0	
search.insights.top_queries.exporter.remote.enabled	b	D	"false"		
search.insights.top_queries.exporter.remote.path	s	D	"query-insights"		
search.insights.top_queries.exporter.remote.repository	s	D	""		
search.insights.top_queries.exporter.type	s	D	"local_index"		
search.insights.top_queries.filter_by_mode	s	D	"none"		
search.insights.top_queries.grouping.attributes.field_name	b	D	"true"		
search.insights.top_queries.grouping.attributes.field_type	b	D	"true"		
search.insights.top_queries.grouping.group_by	s	D	"none"		
search.insights.top_queries.grouping.max_groups_excluding_topn	i	D	"100"	0	
search.insights.top_queries.latency.enabled	b	D	"true"		
search.insights.top_queries.latency.top_n_size	i	D	"10"	1	
search.insights.top_queries.latency.window_size	t	D	"5m"	1m	
search.insights.top_queries.max_source_length	i	D	"524288"	0	
search.insights.top_queries.memory.enabled	b	D	"true"		
search.insights.top_queries.memory.top_n_size	i	D	"10"	1	
search.insights.top_queries.memory.window_size	t	D	"5m"	1m	
search.keyword_index_or_doc_values_enabled	b	D	"false"		
search.low_level_cancellation	b	D	"true"		
search.max_aggregation_rewrite_filters	i	D	"3000"	0	
search.max_buckets	i	D	"65535"	0	
search.max_keep_alive	t	D	"24h"	0ms	
search.max_open_pit_context	i	D	"300"	0	
search.max_open_scroll_context	i	D	"500"	0	
search.phase_took_enabled	b	D	"false"		
search.query.max_query_string_length	i	D	"32000"	1	
search.query.max_query_string_length_monitor_only	b	D	"false"		
search.query.metrics.enabled	b	D	"false"		
search.query_rewriting.enabled	b	D	"false"		
search.query_rewriting.terms_threshold	i	D	"16"	2	
search.request_stats_enabled	b	D	"true"		
search_backpressure.cancellation_burst	d	D	"10.0"	1.0	
search_backpressure.cancellation_rate	d	D	"0.003"		
search_backpressure.cancellation_ratio	d	D	"0.1"		
search_backpressure.mode	s	D	"monitor_only"		
search_backpressure.node_duress.cpu_threshold	d	D	"0.9"	0.0	1.0
search_backpressure.node_duress.heap_threshold	d	D	"0.7"	0.0	1.0
search_backpressure.node_duress.native_memory_limit	z	D	"0b"		
search_backpressure.node_duress.native_memory_threshold	d	D	"0.85"	0.0	1.0
search_backpressure.node_duress.num_successive_breaches	i	D	"3"	1	
search_backpressure.search_shard_task.cancellation_burst	d	D	"10.0"	1.0	
search_backpressure.search_shard_task.cancellation_rate	d	D	"0.003"		
search_backpressure.search_shard_task.cancellation_ratio	d	D	"0.1"		
search_backpressure.search_shard_task.cpu_time_millis_threshold	l	D	"15000"	0	
search_backpressure.search_shard_task.elapsed_time_millis_threshold	l	D	"30000"	0	
search_backpressure.search_shard_task.heap_moving_average_window_size	i	D	"100"	0	
search_backpressure.search_shard_task.heap_percent_threshold	d	D	"0.005"	0.0	1.0
search_backpressure.search_shard_task.heap_variance	d	D	"2.0"	0.0	
search_backpressure.search_shard_task.native_memory_percent_threshold	d	D	"0.05"	0.0	1.0
search_backpressure.search_shard_task.total_heap_percent_threshold	d	D	"0.05"	0.0	1.0
search_backpressure.search_task.cancellation_burst	d	D	"5.0"	1.0	
search_backpressure.search_task.cancellation_rate	d	D	"0.003"		
search_backpressure.search_task.cancellation_ratio	d	D	"0.1"		
search_backpressure.search_task.cpu_time_millis_threshold	l	D	"30000"	0	
search_backpressure.search_task.elapsed_time_millis_threshold	l	D	"45000"	0	
search_backpressure.search_task.heap_moving_average_window_size	i	D	"100"	0	
search_backpressure.search_task.heap_percent_threshold	d	D	"0.02"	0.0	1.0
search_backpressure.search_task.heap_variance	d	D	"2.0"	0.0	
search_backpressure.search_task.native_memory_percent_threshold	d	D	"0.05"	0.0	1.0
search_backpressure.search_task.total_heap_percent_threshold	d	D	"0.05"	0.0	1.0
segrep.pressure.checkpoint.limit	i	D	"30"	1	
segrep.pressure.enabled	b	D	"false"		
segrep.pressure.replica.stale.limit	d	D	"0.5"	0.0	1.0
segrep.pressure.time.limit	t	D	"5m"	0ms	
segrep.replication.time.limit	t	D	"0m"	0ms	
shard_indexing_pressure.cache_store.max_size	i	D	"200"	100	
shard_indexing_pressure.enabled	b	D	"false"		
shard_indexing_pressure.enforced	b	D	"false"		
shard_indexing_pressure.operating_factor.lower	d	D	"0.75"	0.0	
shard_indexing_pressure.operating_factor.optimal	d	D	"0.85"	0.0	
shard_indexing_pressure.operating_factor.upper	d	D	"0.95"	0.0	
shard_indexing_pressure.primary_parameter.node.soft_limit	d	D	"0.7"	0.0	
shard_indexing_pressure.primary_parameter.shard.min_limit	d	D	"0.001"	0.0	
shard_indexing_pressure.secondary_parameter.successful_request.elapsed_timeout	t	D	"300000ms"	0ms	
shard_indexing_pressure.secondary_parameter.successful_request.max_outstanding_requests	i	D	"100"		
shard_indexing_pressure.secondary_parameter.throughput.degradation_factor	d	D	"5.0"	1.0	
shard_indexing_pressure.secondary_parameter.throughput.request_size_window	i	D	"2000"		
snapshot.max_concurrent_operations	i	D	"1000"	1	
snapshot.max_shards_allowed_in_status_api	i	D	"200000"	1	
stream.search.enabled	b	D	"false"		
task_cancellation.duration_millis	l	D	"10000"		
task_cancellation.enabled	b	D	"true"		
task_resource_consumers.enabled	b	D	"false"		
task_resource_tracking.binary_header.enabled	b	D	"true"		
task_resource_tracking.enabled	b	D	"true"		
thread_pool.index_searcher.queue_size	i	D	"1000"		
thread_pool.search.queue_size	i	D	"1000"		
thread_pool.search_throttled.queue_size	i	D	"100"		
thread_pool.stream_search.queue_size	i	D	"1000"		
tiering.prepare.replica_sync_timeout	t	D	"30s"	5s	5m
tiering.service.prefetch.read_ahead.block_count	i	D	"4"	0	
tiering.service.prefetch.stored_fields.enabled	b	D	"true"		
transport.slow_operation_logging_threshold	t	D	"5s"	0ms	
transport.stream.request_timeout	t	D	"5m"		
transport.tracer.exclude	L	D	["internal:coordination/fault_detection/*", "cluster:monitor/nodes/liveness"]		
transport.tracer.include	L	D	[]		
ubi.dataprepper.url	s	D	""		
wlm.workload_group.duress_streak	i	D	"3"	3	
wlm.workload_group.enforcement_interval	l	D	"1000"	1000	
wlm.workload_group.mode	s	D	"monitor_only"		
wlm.workload_group.node.cpu_cancellation_threshold	d	D	"0.9"	4.9E-324	
wlm.workload_group.node.cpu_rejection_threshold	d	D	"0.8"	4.9E-324	
wlm.workload_group.node.memory_cancellation_threshold	d	D	"0.9"	4.9E-324	
wlm.workload_group.node.memory_rejection_threshold	d	D	"0.8"	4.9E-324	
`
